import {
  amber,
  amberA,
  amberDark,
  amberDarkA,
  blue,
  blueA,
  blueDark,
  blueDarkA,
  bronze,
  bronzeA,
  bronzeDark,
  bronzeDarkA,
  brown,
  brownA,
  brownDark,
  brownDarkA,
  crimson,
  crimsonA,
  crimsonDark,
  crimsonDarkA,
  cyan,
  cyanA,
  cyanDark,
  cyanDarkA,
  gold,
  goldA,
  goldDark,
  goldDarkA,
  grass,
  grassA,
  grassDark,
  grassDarkA,
  gray,
  grayA,
  grayDark,
  grayDarkA,
  green,
  greenA,
  greenDark,
  greenDarkA,
  indigo,
  indigoA,
  indigoDark,
  indigoDarkA,
  lime,
  limeA,
  limeDark,
  limeDarkA,
  mauve,
  mauveA,
  mauveDark,
  mauveDarkA,
  mint,
  mintA,
  mintDark,
  mintDarkA,
  olive,
  oliveA,
  oliveDark,
  oliveDarkA,
  orange,
  orangeA,
  orangeDark,
  orangeDarkA,
  pink,
  pinkA,
  pinkDark,
  pinkDarkA,
  plum,
  plumA,
  plumDark,
  plumDarkA,
  purple,
  purpleA,
  purpleDark,
  purpleDarkA,
  red,
  redA,
  redDark,
  redDarkA,
  sage,
  sageA,
  sageDark,
  sageDarkA,
  sand,
  sandA,
  sandDark,
  sandDarkA,
  sky,
  skyA,
  skyDark,
  skyDarkA,
  slate,
  slateA,
  slateDark,
  slateDarkA,
  teal,
  tealA,
  tealDark,
  tealDarkA,
  tomato,
  tomatoA,
  tomatoDark,
  tomatoDarkA,
  violet,
  violetA,
  violetDark,
  violetDarkA,
  yellow,
  yellowA,
  yellowDark,
  yellowDarkA,
} from '@radix-ui/colors'
import { createThemeContract } from '@vanilla-extract/css'
import { createGlobalTheme } from '@vanilla-extract/css'

export const themeVars = createThemeContract({
  amber1: null,
  amber2: null,
  amber3: null,
  amber4: null,
  amber5: null,
  amber6: null,
  amber7: null,
  amber8: null,
  amber9: null,
  amber10: null,
  amber11: null,
  amber12: null,

  amberA1: null,
  amberA2: null,
  amberA3: null,
  amberA4: null,
  amberA5: null,
  amberA6: null,
  amberA7: null,
  amberA8: null,
  amberA9: null,
  amberA10: null,
  amberA11: null,
  amberA12: null,

  blue1: null,
  blue2: null,
  blue3: null,
  blue4: null,
  blue5: null,
  blue6: null,
  blue7: null,
  blue8: null,
  blue9: null,
  blue10: null,
  blue11: null,
  blue12: null,

  blueA1: null,
  blueA2: null,
  blueA3: null,
  blueA4: null,
  blueA5: null,
  blueA6: null,
  blueA7: null,
  blueA8: null,
  blueA9: null,
  blueA10: null,
  blueA11: null,
  blueA12: null,

  bronze1: null,
  bronze2: null,
  bronze3: null,
  bronze4: null,
  bronze5: null,
  bronze6: null,
  bronze7: null,
  bronze8: null,
  bronze9: null,
  bronze10: null,
  bronze11: null,
  bronze12: null,

  bronzeA1: null,
  bronzeA2: null,
  bronzeA3: null,
  bronzeA4: null,
  bronzeA5: null,
  bronzeA6: null,
  bronzeA7: null,
  bronzeA8: null,
  bronzeA9: null,
  bronzeA10: null,
  bronzeA11: null,
  bronzeA12: null,

  brown1: null,
  brown2: null,
  brown3: null,
  brown4: null,
  brown5: null,
  brown6: null,
  brown7: null,
  brown8: null,
  brown9: null,
  brown10: null,
  brown11: null,
  brown12: null,

  brownA1: null,
  brownA2: null,
  brownA3: null,
  brownA4: null,
  brownA5: null,
  brownA6: null,
  brownA7: null,
  brownA8: null,
  brownA9: null,
  brownA10: null,
  brownA11: null,
  brownA12: null,

  crimson1: null,
  crimson2: null,
  crimson3: null,
  crimson4: null,
  crimson5: null,
  crimson6: null,
  crimson7: null,
  crimson8: null,
  crimson9: null,
  crimson10: null,
  crimson11: null,
  crimson12: null,

  crimsonA1: null,
  crimsonA2: null,
  crimsonA3: null,
  crimsonA4: null,
  crimsonA5: null,
  crimsonA6: null,
  crimsonA7: null,
  crimsonA8: null,
  crimsonA9: null,
  crimsonA10: null,
  crimsonA11: null,
  crimsonA12: null,

  cyan1: null,
  cyan2: null,
  cyan3: null,
  cyan4: null,
  cyan5: null,
  cyan6: null,
  cyan7: null,
  cyan8: null,
  cyan9: null,
  cyan10: null,
  cyan11: null,
  cyan12: null,

  cyanA1: null,
  cyanA2: null,
  cyanA3: null,
  cyanA4: null,
  cyanA5: null,
  cyanA6: null,
  cyanA7: null,
  cyanA8: null,
  cyanA9: null,
  cyanA10: null,
  cyanA11: null,
  cyanA12: null,

  gold1: null,
  gold2: null,
  gold3: null,
  gold4: null,
  gold5: null,
  gold6: null,
  gold7: null,
  gold8: null,
  gold9: null,
  gold10: null,
  gold11: null,
  gold12: null,

  goldA1: null,
  goldA2: null,
  goldA3: null,
  goldA4: null,
  goldA5: null,
  goldA6: null,
  goldA7: null,
  goldA8: null,
  goldA9: null,
  goldA10: null,
  goldA11: null,
  goldA12: null,

  grass1: null,
  grass2: null,
  grass3: null,
  grass4: null,
  grass5: null,
  grass6: null,
  grass7: null,
  grass8: null,
  grass9: null,
  grass10: null,
  grass11: null,
  grass12: null,

  grassA1: null,
  grassA2: null,
  grassA3: null,
  grassA4: null,
  grassA5: null,
  grassA6: null,
  grassA7: null,
  grassA8: null,
  grassA9: null,
  grassA10: null,
  grassA11: null,
  grassA12: null,

  gray1: null,
  gray2: null,
  gray3: null,
  gray4: null,
  gray5: null,
  gray6: null,
  gray7: null,
  gray8: null,
  gray9: null,
  gray10: null,
  gray11: null,
  gray12: null,

  grayA1: null,
  grayA2: null,
  grayA3: null,
  grayA4: null,
  grayA5: null,
  grayA6: null,
  grayA7: null,
  grayA8: null,
  grayA9: null,
  grayA10: null,
  grayA11: null,
  grayA12: null,

  green1: null,
  green2: null,
  green3: null,
  green4: null,
  green5: null,
  green6: null,
  green7: null,
  green8: null,
  green9: null,
  green10: null,
  green11: null,
  green12: null,

  greenA1: null,
  greenA2: null,
  greenA3: null,
  greenA4: null,
  greenA5: null,
  greenA6: null,
  greenA7: null,
  greenA8: null,
  greenA9: null,
  greenA10: null,
  greenA11: null,
  greenA12: null,

  indigo1: null,
  indigo2: null,
  indigo3: null,
  indigo4: null,
  indigo5: null,
  indigo6: null,
  indigo7: null,
  indigo8: null,
  indigo9: null,
  indigo10: null,
  indigo11: null,
  indigo12: null,

  indigoA1: null,
  indigoA2: null,
  indigoA3: null,
  indigoA4: null,
  indigoA5: null,
  indigoA6: null,
  indigoA7: null,
  indigoA8: null,
  indigoA9: null,
  indigoA10: null,
  indigoA11: null,
  indigoA12: null,

  lime1: null,
  lime2: null,
  lime3: null,
  lime4: null,
  lime5: null,
  lime6: null,
  lime7: null,
  lime8: null,
  lime9: null,
  lime10: null,
  lime11: null,
  lime12: null,

  limeA1: null,
  limeA2: null,
  limeA3: null,
  limeA4: null,
  limeA5: null,
  limeA6: null,
  limeA7: null,
  limeA8: null,
  limeA9: null,
  limeA10: null,
  limeA11: null,
  limeA12: null,

  mauve1: null,
  mauve2: null,
  mauve3: null,
  mauve4: null,
  mauve5: null,
  mauve6: null,
  mauve7: null,
  mauve8: null,
  mauve9: null,
  mauve10: null,
  mauve11: null,
  mauve12: null,

  mauveA1: null,
  mauveA2: null,
  mauveA3: null,
  mauveA4: null,
  mauveA5: null,
  mauveA6: null,
  mauveA7: null,
  mauveA8: null,
  mauveA9: null,
  mauveA10: null,
  mauveA11: null,
  mauveA12: null,

  mint1: null,
  mint2: null,
  mint3: null,
  mint4: null,
  mint5: null,
  mint6: null,
  mint7: null,
  mint8: null,
  mint9: null,
  mint10: null,
  mint11: null,
  mint12: null,

  mintA1: null,
  mintA2: null,
  mintA3: null,
  mintA4: null,
  mintA5: null,
  mintA6: null,
  mintA7: null,
  mintA8: null,
  mintA9: null,
  mintA10: null,
  mintA11: null,
  mintA12: null,

  olive1: null,
  olive2: null,
  olive3: null,
  olive4: null,
  olive5: null,
  olive6: null,
  olive7: null,
  olive8: null,
  olive9: null,
  olive10: null,
  olive11: null,
  olive12: null,

  oliveA1: null,
  oliveA2: null,
  oliveA3: null,
  oliveA4: null,
  oliveA5: null,
  oliveA6: null,
  oliveA7: null,
  oliveA8: null,
  oliveA9: null,
  oliveA10: null,
  oliveA11: null,
  oliveA12: null,

  orange1: null,
  orange2: null,
  orange3: null,
  orange4: null,
  orange5: null,
  orange6: null,
  orange7: null,
  orange8: null,
  orange9: null,
  orange10: null,
  orange11: null,
  orange12: null,

  orangeA1: null,
  orangeA2: null,
  orangeA3: null,
  orangeA4: null,
  orangeA5: null,
  orangeA6: null,
  orangeA7: null,
  orangeA8: null,
  orangeA9: null,
  orangeA10: null,
  orangeA11: null,
  orangeA12: null,

  pink1: null,
  pink2: null,
  pink3: null,
  pink4: null,
  pink5: null,
  pink6: null,
  pink7: null,
  pink8: null,
  pink9: null,
  pink10: null,
  pink11: null,
  pink12: null,

  pinkA1: null,
  pinkA2: null,
  pinkA3: null,
  pinkA4: null,
  pinkA5: null,
  pinkA6: null,
  pinkA7: null,
  pinkA8: null,
  pinkA9: null,
  pinkA10: null,
  pinkA11: null,
  pinkA12: null,

  plum1: null,
  plum2: null,
  plum3: null,
  plum4: null,
  plum5: null,
  plum6: null,
  plum7: null,
  plum8: null,
  plum9: null,
  plum10: null,
  plum11: null,
  plum12: null,

  plumA1: null,
  plumA2: null,
  plumA3: null,
  plumA4: null,
  plumA5: null,
  plumA6: null,
  plumA7: null,
  plumA8: null,
  plumA9: null,
  plumA10: null,
  plumA11: null,
  plumA12: null,

  purple1: null,
  purple2: null,
  purple3: null,
  purple4: null,
  purple5: null,
  purple6: null,
  purple7: null,
  purple8: null,
  purple9: null,
  purple10: null,
  purple11: null,
  purple12: null,

  purpleA1: null,
  purpleA2: null,
  purpleA3: null,
  purpleA4: null,
  purpleA5: null,
  purpleA6: null,
  purpleA7: null,
  purpleA8: null,
  purpleA9: null,
  purpleA10: null,
  purpleA11: null,
  purpleA12: null,

  red1: null,
  red2: null,
  red3: null,
  red4: null,
  red5: null,
  red6: null,
  red7: null,
  red8: null,
  red9: null,
  red10: null,
  red11: null,
  red12: null,

  redA1: null,
  redA2: null,
  redA3: null,
  redA4: null,
  redA5: null,
  redA6: null,
  redA7: null,
  redA8: null,
  redA9: null,
  redA10: null,
  redA11: null,
  redA12: null,

  sage1: null,
  sage2: null,
  sage3: null,
  sage4: null,
  sage5: null,
  sage6: null,
  sage7: null,
  sage8: null,
  sage9: null,
  sage10: null,
  sage11: null,
  sage12: null,

  sageA1: null,
  sageA2: null,
  sageA3: null,
  sageA4: null,
  sageA5: null,
  sageA6: null,
  sageA7: null,
  sageA8: null,
  sageA9: null,
  sageA10: null,
  sageA11: null,
  sageA12: null,

  sand1: null,
  sand2: null,
  sand3: null,
  sand4: null,
  sand5: null,
  sand6: null,
  sand7: null,
  sand8: null,
  sand9: null,
  sand10: null,
  sand11: null,
  sand12: null,

  sandA1: null,
  sandA2: null,
  sandA3: null,
  sandA4: null,
  sandA5: null,
  sandA6: null,
  sandA7: null,
  sandA8: null,
  sandA9: null,
  sandA10: null,
  sandA11: null,
  sandA12: null,

  sky1: null,
  sky2: null,
  sky3: null,
  sky4: null,
  sky5: null,
  sky6: null,
  sky7: null,
  sky8: null,
  sky9: null,
  sky10: null,
  sky11: null,
  sky12: null,

  skyA1: null,
  skyA2: null,
  skyA3: null,
  skyA4: null,
  skyA5: null,
  skyA6: null,
  skyA7: null,
  skyA8: null,
  skyA9: null,
  skyA10: null,
  skyA11: null,
  skyA12: null,

  slate1: null,
  slate2: null,
  slate3: null,
  slate4: null,
  slate5: null,
  slate6: null,
  slate7: null,
  slate8: null,
  slate9: null,
  slate10: null,
  slate11: null,
  slate12: null,

  slateA1: null,
  slateA2: null,
  slateA3: null,
  slateA4: null,
  slateA5: null,
  slateA6: null,
  slateA7: null,
  slateA8: null,
  slateA9: null,
  slateA10: null,
  slateA11: null,
  slateA12: null,

  teal1: null,
  teal2: null,
  teal3: null,
  teal4: null,
  teal5: null,
  teal6: null,
  teal7: null,
  teal8: null,
  teal9: null,
  teal10: null,
  teal11: null,
  teal12: null,

  tealA1: null,
  tealA2: null,
  tealA3: null,
  tealA4: null,
  tealA5: null,
  tealA6: null,
  tealA7: null,
  tealA8: null,
  tealA9: null,
  tealA10: null,
  tealA11: null,
  tealA12: null,

  tomato1: null,
  tomato2: null,
  tomato3: null,
  tomato4: null,
  tomato5: null,
  tomato6: null,
  tomato7: null,
  tomato8: null,
  tomato9: null,
  tomato10: null,
  tomato11: null,
  tomato12: null,

  tomatoA1: null,
  tomatoA2: null,
  tomatoA3: null,
  tomatoA4: null,
  tomatoA5: null,
  tomatoA6: null,
  tomatoA7: null,
  tomatoA8: null,
  tomatoA9: null,
  tomatoA10: null,
  tomatoA11: null,
  tomatoA12: null,

  violet1: null,
  violet2: null,
  violet3: null,
  violet4: null,
  violet5: null,
  violet6: null,
  violet7: null,
  violet8: null,
  violet9: null,
  violet10: null,
  violet11: null,
  violet12: null,

  violetA1: null,
  violetA2: null,
  violetA3: null,
  violetA4: null,
  violetA5: null,
  violetA6: null,
  violetA7: null,
  violetA8: null,
  violetA9: null,
  violetA10: null,
  violetA11: null,
  violetA12: null,

  yellow1: null,
  yellow2: null,
  yellow3: null,
  yellow4: null,
  yellow5: null,
  yellow6: null,
  yellow7: null,
  yellow8: null,
  yellow9: null,
  yellow10: null,
  yellow11: null,
  yellow12: null,

  yellowA1: null,
  yellowA2: null,
  yellowA3: null,
  yellowA4: null,
  yellowA5: null,
  yellowA6: null,
  yellowA7: null,
  yellowA8: null,
  yellowA9: null,
  yellowA10: null,
  yellowA11: null,
  yellowA12: null,
} as const)

createGlobalTheme('[data-wish-theme=dark]', themeVars, {
  ...amberDark,
  ...amberDarkA,
  ...blueDark,
  ...blueDarkA,
  ...bronzeDark,
  ...bronzeDarkA,
  ...brownDark,
  ...brownDarkA,
  ...crimsonDark,
  ...crimsonDarkA,
  ...cyanDark,
  ...cyanDarkA,
  ...goldDark,
  ...goldDarkA,
  ...grassDark,
  ...grassDarkA,
  ...grayDark,
  ...grayDarkA,
  ...greenDark,
  ...greenDarkA,
  ...indigoDark,
  ...indigoDarkA,
  ...limeDark,
  ...limeDarkA,
  ...mauveDark,
  ...mauveDarkA,
  ...mintDark,
  ...mintDarkA,
  ...oliveDark,
  ...oliveDarkA,
  ...orangeDark,
  ...orangeDarkA,
  ...pinkDark,
  ...pinkDarkA,
  ...plumDark,
  ...plumDarkA,
  ...purpleDark,
  ...purpleDarkA,
  ...redDark,
  ...redDarkA,
  ...sageDark,
  ...sageDarkA,
  ...sandDark,
  ...sandDarkA,
  ...skyDark,
  ...skyDarkA,
  ...slateDark,
  ...slateDarkA,
  ...tealDark,
  ...tealDarkA,
  ...tomatoDark,
  ...tomatoDarkA,
  ...violetDark,
  ...violetDarkA,
  ...yellowDark,
  ...yellowDarkA,
})

createGlobalTheme('[data-wish-theme=light]', themeVars, {
  ...amber,
  ...amberA,
  ...blue,
  ...blueA,
  ...bronze,
  ...bronzeA,
  ...brown,
  ...brownA,
  ...crimson,
  ...crimsonA,
  ...cyan,
  ...cyanA,
  ...gold,
  ...goldA,
  ...grass,
  ...grassA,
  ...gray,
  ...grayA,
  ...green,
  ...greenA,
  ...indigo,
  ...indigoA,
  ...lime,
  ...limeA,
  ...mauve,
  ...mauveA,
  ...mint,
  ...mintA,
  ...olive,
  ...oliveA,
  ...orange,
  ...orangeA,
  ...pink,
  ...pinkA,
  ...plum,
  ...plumA,
  ...purple,
  ...purpleA,
  ...red,
  ...redA,
  ...sage,
  ...sageA,
  ...sand,
  ...sandA,
  ...sky,
  ...skyA,
  ...slate,
  ...slateA,
  ...teal,
  ...tealA,
  ...tomato,
  ...tomatoA,
  ...violet,
  ...violetA,
  ...yellow,
  ...yellowA,
})
