import { createThemeContract } from '@vanilla-extract/css'
import { createGlobalTheme } from '@vanilla-extract/css'

import * as colors from './colors'

export const themeVars = createThemeContract({
  amber1: null,
  amber2: null,
  amber3: null,
  amber4: null,
  amber5: null,
  amber6: null,
  amber7: null,
  amber8: null,
  amber9: null,
  amber10: null,
  amber11: null,
  amber12: null,

  blue1: null,
  blue2: null,
  blue3: null,
  blue4: null,
  blue5: null,
  blue6: null,
  blue7: null,
  blue8: null,
  blue9: null,
  blue10: null,
  blue11: null,
  blue12: null,

  bronze1: null,
  bronze2: null,
  bronze3: null,
  bronze4: null,
  bronze5: null,
  bronze6: null,
  bronze7: null,
  bronze8: null,
  bronze9: null,
  bronze10: null,
  bronze11: null,
  bronze12: null,

  brown1: null,
  brown2: null,
  brown3: null,
  brown4: null,
  brown5: null,
  brown6: null,
  brown7: null,
  brown8: null,
  brown9: null,
  brown10: null,
  brown11: null,
  brown12: null,

  crimson1: null,
  crimson2: null,
  crimson3: null,
  crimson4: null,
  crimson5: null,
  crimson6: null,
  crimson7: null,
  crimson8: null,
  crimson9: null,
  crimson10: null,
  crimson11: null,
  crimson12: null,

  cyan1: null,
  cyan2: null,
  cyan3: null,
  cyan4: null,
  cyan5: null,
  cyan6: null,
  cyan7: null,
  cyan8: null,
  cyan9: null,
  cyan10: null,
  cyan11: null,
  cyan12: null,

  gold1: null,
  gold2: null,
  gold3: null,
  gold4: null,
  gold5: null,
  gold6: null,
  gold7: null,
  gold8: null,
  gold9: null,
  gold10: null,
  gold11: null,
  gold12: null,

  grass1: null,
  grass2: null,
  grass3: null,
  grass4: null,
  grass5: null,
  grass6: null,
  grass7: null,
  grass8: null,
  grass9: null,
  grass10: null,
  grass11: null,
  grass12: null,

  gray1: null,
  gray2: null,
  gray3: null,
  gray4: null,
  gray5: null,
  gray6: null,
  gray7: null,
  gray8: null,
  gray9: null,
  gray10: null,
  gray11: null,
  gray12: null,

  green1: null,
  green2: null,
  green3: null,
  green4: null,
  green5: null,
  green6: null,
  green7: null,
  green8: null,
  green9: null,
  green10: null,
  green11: null,
  green12: null,

  indigo1: null,
  indigo2: null,
  indigo3: null,
  indigo4: null,
  indigo5: null,
  indigo6: null,
  indigo7: null,
  indigo8: null,
  indigo9: null,
  indigo10: null,
  indigo11: null,
  indigo12: null,

  lime1: null,
  lime2: null,
  lime3: null,
  lime4: null,
  lime5: null,
  lime6: null,
  lime7: null,
  lime8: null,
  lime9: null,
  lime10: null,
  lime11: null,
  lime12: null,

  mauve1: null,
  mauve2: null,
  mauve3: null,
  mauve4: null,
  mauve5: null,
  mauve6: null,
  mauve7: null,
  mauve8: null,
  mauve9: null,
  mauve10: null,
  mauve11: null,
  mauve12: null,

  mint1: null,
  mint2: null,
  mint3: null,
  mint4: null,
  mint5: null,
  mint6: null,
  mint7: null,
  mint8: null,
  mint9: null,
  mint10: null,
  mint11: null,
  mint12: null,

  olive1: null,
  olive2: null,
  olive3: null,
  olive4: null,
  olive5: null,
  olive6: null,
  olive7: null,
  olive8: null,
  olive9: null,
  olive10: null,
  olive11: null,
  olive12: null,

  orange1: null,
  orange2: null,
  orange3: null,
  orange4: null,
  orange5: null,
  orange6: null,
  orange7: null,
  orange8: null,
  orange9: null,
  orange10: null,
  orange11: null,
  orange12: null,

  pink1: null,
  pink2: null,
  pink3: null,
  pink4: null,
  pink5: null,
  pink6: null,
  pink7: null,
  pink8: null,
  pink9: null,
  pink10: null,
  pink11: null,
  pink12: null,

  plum1: null,
  plum2: null,
  plum3: null,
  plum4: null,
  plum5: null,
  plum6: null,
  plum7: null,
  plum8: null,
  plum9: null,
  plum10: null,
  plum11: null,
  plum12: null,

  purple1: null,
  purple2: null,
  purple3: null,
  purple4: null,
  purple5: null,
  purple6: null,
  purple7: null,
  purple8: null,
  purple9: null,
  purple10: null,
  purple11: null,
  purple12: null,

  red1: null,
  red2: null,
  red3: null,
  red4: null,
  red5: null,
  red6: null,
  red7: null,
  red8: null,
  red9: null,
  red10: null,
  red11: null,
  red12: null,

  sage1: null,
  sage2: null,
  sage3: null,
  sage4: null,
  sage5: null,
  sage6: null,
  sage7: null,
  sage8: null,
  sage9: null,
  sage10: null,
  sage11: null,
  sage12: null,

  sand1: null,
  sand2: null,
  sand3: null,
  sand4: null,
  sand5: null,
  sand6: null,
  sand7: null,
  sand8: null,
  sand9: null,
  sand10: null,
  sand11: null,
  sand12: null,

  sky1: null,
  sky2: null,
  sky3: null,
  sky4: null,
  sky5: null,
  sky6: null,
  sky7: null,
  sky8: null,
  sky9: null,
  sky10: null,
  sky11: null,
  sky12: null,

  slate1: null,
  slate2: null,
  slate3: null,
  slate4: null,
  slate5: null,
  slate6: null,
  slate7: null,
  slate8: null,
  slate9: null,
  slate10: null,
  slate11: null,
  slate12: null,

  teal1: null,
  teal2: null,
  teal3: null,
  teal4: null,
  teal5: null,
  teal6: null,
  teal7: null,
  teal8: null,
  teal9: null,
  teal10: null,
  teal11: null,
  teal12: null,

  tomato1: null,
  tomato2: null,
  tomato3: null,
  tomato4: null,
  tomato5: null,
  tomato6: null,
  tomato7: null,
  tomato8: null,
  tomato9: null,
  tomato10: null,
  tomato11: null,
  tomato12: null,

  violet1: null,
  violet2: null,
  violet3: null,
  violet4: null,
  violet5: null,
  violet6: null,
  violet7: null,
  violet8: null,
  violet9: null,
  violet10: null,
  violet11: null,
  violet12: null,

  yellow1: null,
  yellow2: null,
  yellow3: null,
  yellow4: null,
  yellow5: null,
  yellow6: null,
  yellow7: null,
  yellow8: null,
  yellow9: null,
  yellow10: null,
  yellow11: null,
  yellow12: null,
} as const)

createGlobalTheme('[data-wish-theme=light]', themeVars, {
  ...colors.amber,
  ...colors.blue,
  ...colors.bronze,
  ...colors.brown,
  ...colors.crimson,
  ...colors.cyan,
  ...colors.gold,
  ...colors.grass,
  ...colors.gray,
  ...colors.green,
  ...colors.indigo,
  ...colors.lime,
  ...colors.mauve,
  ...colors.mint,
  ...colors.olive,
  ...colors.orange,
  ...colors.pink,
  ...colors.plum,
  ...colors.purple,
  ...colors.red,
  ...colors.sage,
  ...colors.sand,
  ...colors.sky,
  ...colors.slate,
  ...colors.teal,
  ...colors.tomato,
  ...colors.violet,
  ...colors.yellow,
})

createGlobalTheme('[data-wish-theme=dark]', themeVars, {
  ...colors.amberDark,
  ...colors.blueDark,
  ...colors.bronzeDark,
  ...colors.brownDark,
  ...colors.crimsonDark,
  ...colors.cyanDark,
  ...colors.goldDark,
  ...colors.grassDark,
  ...colors.grayDark,
  ...colors.greenDark,
  ...colors.indigoDark,
  ...colors.limeDark,
  ...colors.mauveDark,
  ...colors.mintDark,
  ...colors.oliveDark,
  ...colors.orangeDark,
  ...colors.pinkDark,
  ...colors.plumDark,
  ...colors.purpleDark,
  ...colors.redDark,
  ...colors.sageDark,
  ...colors.sandDark,
  ...colors.skyDark,
  ...colors.slateDark,
  ...colors.tealDark,
  ...colors.tomatoDark,
  ...colors.violetDark,
  ...colors.yellowDark,
})
